### ISSUE TITLE
Favorite shortcut buggy behaviour

### ISSUE THREAD

**Issue by pawel-tomkiel** [TechStark/jira-favorites-extension#1]
Hey,

thank you for creating this extension, it really helps me with my Jira flow 🙂

I noticed though that sometimes random Jira issues are being (un-)favorited which messes up list for me (I use it for accessing daily focus tasks). I'd blame `f` shortcut for this:

https://github.com/TechStark/jira-favorites-extension/blob/cb91c31d9dbeea12bfd0755924fb1e00f0b37c06/src/content-script.js#L31-L38

Is there any way of disabling it, or better changing it from `f` to at least two-keys-combination to not use it accidentally without knowing it?

**Comment by ttt43ttt** [comment]
@pawel-tomkiel thanks for your feedback. I've changed to "Alt + Shift + f", and submitted to Chrome extension store. It should be available in a few days.

**Comment by pawel-tomkiel** [comment]
that was way faster than expected, thank you!
